// Expo config plugin: disable bitcode for every Pod target.
//
// This project uses Expo's managed workflow, so `ios/Podfile` is not checked
// in — it is generated by `expo prebuild` on every EAS build. To customise the
// Podfile we inject into the generated file at prebuild time via a dangerous
// mod rather than editing a committed Podfile (which would be overwritten).
//
// The injected block does two things, both required for
// `amazon-ivs-react-native-broadcast`:
//
//   1. Disables ENABLE_BITCODE for all Pod targets. This controls how the
//      pods compiled from source are built (bitcode is deprecated in modern
//      Xcode), but it has NO effect on precompiled binaries.
//   2. Strips bitcode from the AmazonIVSBroadcast framework binary. That SDK
//      ships as a precompiled framework that was built WITH bitcode, so the
//      ENABLE_BITCODE setting never touches it and App Store Connect rejects
//      the upload ("Invalid Executable ... contains bitcode", 409). Running
//      `xcrun bitcode_strip -r` on the binary removes the bitcode so the
//      archive validates.

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const ANCHOR = 'post_install do |installer|';
const MARKER = '# @generated by withDisableBitcode config plugin';
const SNIPPET = [
  `    ${MARKER}`,
  '    installer.pods_project.targets.each do |target|',
  '      target.build_configurations.each do |config|',
  "        config.build_settings['ENABLE_BITCODE'] = 'NO'",
  '      end',
  '    end',
  '    # AmazonIVSBroadcast ships precompiled WITH bitcode, which ENABLE_BITCODE',
  '    # above cannot remove. Strip it from the binary so App Store Connect',
  '    # accepts the upload (otherwise: Invalid Executable ... contains bitcode).',
  '    bitcode_strip = `xcrun --find bitcode_strip`.strip',
  "    Dir.glob(File.join(installer.sandbox.root.to_s, '**', 'AmazonIVSBroadcast.framework', 'AmazonIVSBroadcast')).each do |binary|",
  '      puts "[withDisableBitcode] stripping bitcode from #{binary}"',
  "      system(bitcode_strip, binary, '-r', '-o', binary)",
  '    end',
].join('\n');

module.exports = function withDisableBitcode(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(
        cfg.modRequest.platformProjectRoot,
        'Podfile'
      );
      let contents = fs.readFileSync(podfilePath, 'utf8');

      // Idempotent: never inject twice.
      if (!contents.includes(MARKER)) {
        if (contents.includes(ANCHOR)) {
          // CocoaPods allows only one post_install hook, so inject into the
          // existing block generated by Expo rather than adding a second one.
          contents = contents.replace(ANCHOR, `${ANCHOR}\n${SNIPPET}`);
        } else {
          contents += `\n\n${ANCHOR}\n${SNIPPET}\nend\n`;
        }
        fs.writeFileSync(podfilePath, contents);
      }

      return cfg;
    },
  ]);
};
