// Expo config plugin: disable bitcode for every Pod target.
//
// This project uses Expo's managed workflow, so `ios/Podfile` is not checked
// in — it is generated by `expo prebuild` on every EAS build. To customise the
// Podfile we inject into the generated file at prebuild time via a dangerous
// mod rather than editing a committed Podfile (which would be overwritten).
//
// The injected block disables ENABLE_BITCODE for all Pod targets, which is
// required for `amazon-ivs-react-native-broadcast` (the AmazonIVSBroadcast
// SDK ships without bitcode). Bitcode is also deprecated in modern Xcode.

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const ANCHOR = 'post_install do |installer|';
const MARKER = '# @generated by withDisableBitcode config plugin';
const SNIPPET = [
  `    ${MARKER}`,
  '    installer.pods_project.targets.each do |target|',
  '      target.build_configurations.each do |config|',
  "        config.build_settings['ENABLE_BITCODE'] = 'NO'",
  '      end',
  '    end',
].join('\n');

module.exports = function withDisableBitcode(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(
        cfg.modRequest.platformProjectRoot,
        'Podfile'
      );
      let contents = fs.readFileSync(podfilePath, 'utf8');

      // Idempotent: never inject twice.
      if (!contents.includes(MARKER)) {
        if (contents.includes(ANCHOR)) {
          // CocoaPods allows only one post_install hook, so inject into the
          // existing block generated by Expo rather than adding a second one.
          contents = contents.replace(ANCHOR, `${ANCHOR}\n${SNIPPET}`);
        } else {
          contents += `\n\n${ANCHOR}\n${SNIPPET}\nend\n`;
        }
        fs.writeFileSync(podfilePath, contents);
      }

      return cfg;
    },
  ]);
};
